-- Create Database
CREATE DATABASE IF NOT EXISTS JOB_ANALYTICS;

USE DATABASE JOB_ANALYTICS;

-- Create Schemas
CREATE SCHEMA IF NOT EXISTS RAW_DATA;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

-- Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
WITH 
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Use the warehouse
USE WAREHOUSE COMPUTE_WH;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ACCOUNTADMIN;
GRANT ALL ON DATABASE JOB_ANALYTICS TO ROLE ACCOUNTADMIN;
GRANT ALL ON SCHEMA JOB_ANALYTICS.RAW_DATA TO ROLE ACCOUNTADMIN;
GRANT ALL ON SCHEMA JOB_ANALYTICS.STAGING TO ROLE ACCOUNTADMIN;
GRANT ALL ON SCHEMA JOB_ANALYTICS.ANALYTICS TO ROLE ACCOUNTADMIN;
